services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Mount the directory you want to browse - adjust this path as needed
      - ${MAIN_FB_SERVICE_PATH}:/srv
      # Persistent database and config
      - ${MAIN_FB_CONFIG_PATH}/database:/database
      - ${MAIN_FB_CONFIG_PATH}/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    command: >
      --database /database/filebrowser.db
      --config /config/config.json
      --root /srv
      --port 80
      --address 0.0.0.0

networks:
  default:
    name: filebrowser-network
